install:                                                                                                            
    pip install -r requirements.txt                                                                                 
                                                                                                                     
run:                                                                                                                
    uvicorn main:app --reload                                                                                       
                                                                                                                     
run_prod:  # For production, consider removing --reload                                                             
    uvicorn main:app --host 0.0.0.0 --port 8000  